name: Free up disk space
description: Free up disk space on Ubuntu runners
inputs:
  desired-space:
    description: Desired free space in MB
    required: true
    default: "20000"
outputs:
  available-space:
    description: Available space
    value: ${{ steps.script.outputs.available-space }}

runs:
  using: "composite"
  steps:
    - name: Run script
      id: script
      run: sudo GITHUB_OUTPUT="$GITHUB_OUTPUT" node "$GITHUB_ACTION_PATH/diskspace.js" ~/filler.dat "${{ inputs.desired-space }}"
      shell: bash
