on:
  push:
  workflow_dispatch:

jobs:

  composite-action:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    strategy:
      matrix:
        audit-space:
          - "true"
          - "false"

    steps:
      - uses: manics/action-free-disk-space@main
        id: space
        with:
          desired-space: "30000"
          audit-space: ${{ matrix.audit-space }}

      - run: |
          ls -lh ~
          echo ${{ steps.space.outputs.available-space }}
          sync
          df -h

