on:
  push:
  workflow_dispatch:

jobs:

  df:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    outputs:
      apply: ${{ steps.plan.outputs.apply }}

    steps:
      - uses: actions/checkout@v4

      - id: du
        run: |
          sudo du -m --exclude=/dev --exclude=/proc --exclude=/sys --exclude=/tmp / > du.txt

      # - id: df
      #   run: |
      #     echo "df<<EOF" >> "$GITHUB_OUTPUT"
      #     sudo df -m --output=avail,source,target >> "$GITHUB_OUTPUT"
      #     echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Upload du
        uses: actions/upload-artifact@v4
        with:
          name: du
          path: du.txt

      # - run: sort -n du.txt

      # - run: echo "${{ steps.df.outputs.df }}"

      # - run: df -m

      # - name: Clean some files
      #   run: |
      #     sudo rm -rf \
      #       /usr/local/lib/android \
      #       /usr/local/.ghcup \
      #       /opt/hostedtoolcache/CodeQL \
      #       /opt/microsoft/ \
      #       /usr/local/share \
      #       /usr/share/swift/ \

      # - run: df -m

      - run: node diskspace.js filler.dat 30000
