on:
  push:
  workflow_dispatch:
    inputs:
      apply:
        type: boolean
        description: assume changes
        required: true
        default: true

jobs:

  plan:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    outputs:
      apply: ${{ steps.plan.outputs.apply }}

    steps:
      - name: plan
        id: plan
        run: |
          echo "apply=${{ inputs.apply }}" >> "$GITHUB_OUTPUT"
          date >> test.txt

      - name: Upload plan
        if: steps.plan.outputs.apply
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: test.txt

  apply:
    needs:
      - plan
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    if: needs.plan.outputs.apply
    environment: test-plan-apply

    steps:

      - name: Download plan
        uses: actions/download-artifact@v4
        with:
          name: test

      - name: Apply
        run: |
          cat test.txt
