on: [push]

jobs:

  hello_world_job_without_default_matrix_param:
    runs-on: ubuntu-latest
    name: A job to say hello (without default matrix param)
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false # Do not cancel all jobs if one fails
      matrix:
        experimental:
          - false
        include:
          - text: aaaaa (not experimental)

          - text: bbbbb (experimental)
            experimental: true

          - text: ccc (not experimental)

    steps:
      - run: |
          echo "matrix.text: ${{ matrix.text }}"
          echo "experimental.text: ${{ matrix.experimental }}"


  hello_world_job_with_default_matrix_param:
    runs-on: ubuntu-latest
    name: A job to say hello (with default matrix param)
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false # Do not cancel all jobs if one fails
      matrix:
        include:
          - text: aaaaa (not experimental)
            experimental: false

          - text: bbbbb (experimental)
            experimental: true

          - text: ccccc (not experimental)
            experimental: false

    steps:
      - run: |
          echo "matrix.text: ${{ matrix.text }}"
          echo "experimental.text: ${{ matrix.experimental }}"

  registry-podman-test:
    runs-on: ubuntu-latest
    services:
      registry:
        image: docker.io/library/registry:latest
        ports:
          - 5000:5000

    steps:
      - run: |
          set -x
          IP=$(hostname -I | awk '{print $1}')
          mkdir -p ~/.config/containers/
          cat << EOF > ~/.config/containers/registries.conf
          [[registry]]
          location="$IP:5000"
          insecure=true
          EOF
          
          podman pull docker.io/library/busybox
          podman image tag docker.io/library/busybox "$IP:5000/x/busybox"
          podman push "$IP:5000/x/busybox"
          podman image ls

