on:
  push:
  workflow_dispatch:

jobs:

  plan:
    runs-on: ubuntu-22.04
    timeout-minutes: 2
    outputs:
      apply: ${{ steps.plan.outputs.apply }}

    steps:
      - name: plan
        id: plan
        run: |
          echo "apply=yes" >> "$GITHUB_OUTPUT"
          date >> test.txt

      - name: Upload plan
        if: ${{ steps.plan.outputs.apply }} == "yes"
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: test.txt

  decision:
    needs:
      - plan
    runs-on: ubuntu-22.04
    timeout-minutes: 2
    if: ${{ needs.plan.outputs.apply }} == "yes"

    steps:

      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - run: ls -l

  apply:
    needs:
      - decision
    runs-on: ubuntu-22.04
    timeout-minutes: 2

    steps:

      - name: Download plan
        uses: actions/download-artifact@v3
        with:
          name: test

      - name: Apply
        run: |
          cat test.txt
