on:
  push:
  workflow_dispatch:

jobs:

  networks:
    runs-on: ubuntu-24.04
    timeout-minutes: 4
    steps:
      - run: |
          ip addr show
          ip route show
          hostname -I
          docker network ls

      - name: Create IPv4+IPv6 network
        run: |
          SUBNET=$(python -c 'from random import  randint; print("fc00:" + ":".join(hex(randint(0,2**16))[2:] for _ in range(3)) + "::/64")')
          echo $SUBNET
          docker network create --ipv6 testnet --subnet "$SUBNET" --internal

      - name: show networks
        run: |
          for f in $(docker network ls -q); do
            echo "***** $f *****"
            docker network inspect $f
          done

      - name: Start minimal notebook
        run: |
          docker run -d --name testnotebook --net=testnet quay.io/jupyter/minimal-notebook
          sleep 15

      - name: jupyter_server_config
        run: |
          set -x
          docker exec testnotebook hostname -I
          # curl "http://127.0.0.1:8888/api"
          # curl "http://[::1]:8888/api"
          docker exec testnotebook cat /etc/jupyter/jupyter_server_config.py

      - name: Check public IPv4 connectivity
        run: |
          set -x
          IP4=$(docker inspect testnotebook --format '{{.NetworkSettings.Networks.testnet.IPAddress}}')
          if [ -z "$IP4" ]; then
            echo "Failed to lookup IPv4 for container"
            exit 1
          fi
          docker exec testnotebook curl -sS "http://$IP4:8888/api"

      - name: Check public IPv6 connectivity
        run: |
          set -x
          IP6=$(docker inspect testnotebook --format '{{.NetworkSettings.Networks.testnet.GlobalIPv6Address}}')
          if [ -z "$IP6" ]; then
            echo "Failed to lookup IPv6 for container"
            exit 1
          fi
          curl -f "http://[$IP6]:8888/api"
          docker exec testnotebook curl -sS "http://[$IP6]:8888/api"

      - name: Container
        if: always()
        run: docker inspect testnotebook

      - name: Logs
        if: always()
        run: docker logs testnotebook
